[build]
  base = "/app"
  publish = "build/"
  command = "npm run build"

[build.environment]
  REACT_APP_BACK_URL = "https://db-codding-buddy.herokuapp.com/"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200